/*
  # Create Exits Tracking Schema

  1. New Enums
    - `job_status_type` - Tracks job opening status (Open, On Hold, Filled, Cancelled)
    - `specialty_type` - Healthcare specialties (RN, LPN, CNA, Tech, Therapist)
    - `shift_type` - Work shift patterns (Days, Nights, Rotating, Evenings)
    - `engagement_status_type` - Engagement lifecycle (Offered, Accepted, Active, Completed, Cancelled)
    - `exit_reason` - Reasons for clinician exits (Personal, Completed, etc.)
    - `exit_type` - Exit classification (Voluntary, Involuntary)

  2. New Tables
    - `facilities` - Healthcare facilities where jobs are located
      - `id` (bigint, primary key)
      - `name` (text, unique, required) - Facility name
      - `city` (text, required) - City location
      - `state` (text, required) - State abbreviation
      - `created_at`, `updated_at` (timestamptz)

    - `jobs` - Available job positions at facilities
      - `id` (bigint, primary key)
      - `facility_id` (bigint, foreign key to facilities)
      - `status` (job_status_type, default 'Open')
      - `specialty` (specialty_type, required)
      - `shift` (shift_type, required)
      - `hours_per_week` (integer, required)
      - `start_date` (date, required)
      - `duration_weeks` (integer, default 13)
      - `created_at`, `updated_at` (timestamptz)

    - `engagements` - Active assignments linking prospects to jobs
      - `id` (bigint, primary key)
      - `prospect_id` (bigint, foreign key to prospects, cascade delete)
      - `job_id` (bigint, foreign key to jobs)
      - `status` (engagement_status_type, default 'Active')
      - `start_date` (date, required)
      - `end_date` (date, required)
      - `created_at`, `updated_at` (timestamptz)

    - `exits` - Exit records for clinicians who left assignments
      - `id` (bigint, primary key)
      - `prospect_id` (bigint, foreign key to prospects, cascade delete)
      - `engagement_id` (bigint, foreign key to engagements, nullable)
      - `exit_type` (exit_type, required)
      - `exit_reason` (exit_reason, required)
      - `exit_date` (date, required)
      - `eligible_for_rehire` (boolean, default true)
      - `notes` (text, nullable)
      - `created_at`, `updated_at` (timestamptz)

  3. Indexes
    - Foreign key indexes for performance
    - Status and date indexes for filtering
    - Composite indexes for common queries

  4. Triggers
    - Auto-update `updated_at` timestamps on all tables

  5. Security
    - RLS enabled on all tables
    - Authenticated users have full access to manage exit records
*/

-- =====================================================================
-- Helper Function: Update timestamp on row modification
-- =====================================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- Drop existing objects (idempotent migration)
-- =====================================================================

DROP TABLE IF EXISTS public.exits CASCADE;
DROP TABLE IF EXISTS public.engagements CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE;
DROP TABLE IF EXISTS public.facilities CASCADE;

DROP TYPE IF EXISTS public.exit_reason;
DROP TYPE IF EXISTS public.exit_type;
DROP TYPE IF EXISTS public.engagement_status_type;
DROP TYPE IF EXISTS public.job_status_type;
DROP TYPE IF EXISTS public.specialty_type;
DROP TYPE IF EXISTS public.shift_type;

-- =====================================================================
-- Create ENUM types
-- =====================================================================

CREATE TYPE public.job_status_type AS ENUM ('Open', 'On Hold', 'Filled', 'Cancelled');
CREATE TYPE public.specialty_type AS ENUM ('RN', 'LPN', 'CNA', 'Tech', 'Therapist');
CREATE TYPE public.shift_type AS ENUM ('Days', 'Nights', 'Rotating', 'Evenings');
CREATE TYPE public.engagement_status_type AS ENUM ('Offered', 'Accepted', 'Active', 'Completed', 'Cancelled');
CREATE TYPE public.exit_reason AS ENUM (
  'Personal Reasons',
  'Contract Completed',
  'Facility Decision',
  'Performance Issue',
  'Rate Negotiation',
  'Scheduling Conflict',
  'Better Offer',
  'Relocation',
  'Other'
);
CREATE TYPE public.exit_type AS ENUM ('Voluntary', 'Involuntary');

-- =====================================================================
-- Create facilities table
-- =====================================================================

CREATE TABLE public.facilities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  city text NOT NULL,
  state text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TRIGGER facilities_updated_at
  BEFORE UPDATE ON public.facilities
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================================
-- Create jobs table
-- =====================================================================

CREATE TABLE public.jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id bigint NOT NULL REFERENCES public.facilities(id) ON DELETE RESTRICT,
  status public.job_status_type NOT NULL DEFAULT 'Open',
  specialty public.specialty_type NOT NULL,
  shift public.shift_type NOT NULL,
  hours_per_week integer NOT NULL,
  start_date date NOT NULL,
  duration_weeks integer NOT NULL DEFAULT 13,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_jobs_facility_id ON public.jobs(facility_id);
CREATE INDEX idx_jobs_status ON public.jobs(status);
CREATE INDEX idx_jobs_specialty ON public.jobs(specialty);

CREATE TRIGGER jobs_updated_at
  BEFORE UPDATE ON public.jobs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================================
-- Create engagements table
-- =====================================================================

CREATE TABLE public.engagements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prospect_id bigint NOT NULL REFERENCES public.prospects(id) ON DELETE CASCADE,
  job_id bigint NOT NULL REFERENCES public.jobs(id) ON DELETE RESTRICT,
  status public.engagement_status_type NOT NULL DEFAULT 'Active',
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_engagements_prospect_id ON public.engagements(prospect_id);
CREATE INDEX idx_engagements_job_id ON public.engagements(job_id);
CREATE INDEX idx_engagements_status ON public.engagements(status);

CREATE TRIGGER engagements_updated_at
  BEFORE UPDATE ON public.engagements
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================================
-- Create exits table
-- =====================================================================

CREATE TABLE public.exits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prospect_id bigint NOT NULL REFERENCES public.prospects(id) ON DELETE CASCADE,
  engagement_id bigint REFERENCES public.engagements(id) ON DELETE SET NULL,
  exit_type public.exit_type NOT NULL,
  exit_reason public.exit_reason NOT NULL,
  exit_date date NOT NULL,
  eligible_for_rehire boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_exits_prospect_id ON public.exits(prospect_id);
CREATE INDEX idx_exits_engagement_id ON public.exits(engagement_id);
CREATE INDEX idx_exits_exit_date ON public.exits(exit_date DESC);
CREATE INDEX idx_exits_exit_reason ON public.exits(exit_reason);

CREATE TRIGGER exits_updated_at
  BEFORE UPDATE ON public.exits
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================================
-- Row Level Security (RLS)
-- =====================================================================

-- Enable RLS on all tables
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engagements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exits ENABLE ROW LEVEL SECURITY;

-- Facilities policies
CREATE POLICY "Authenticated users can read facilities"
  ON public.facilities FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert facilities"
  ON public.facilities FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update facilities"
  ON public.facilities FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete facilities"
  ON public.facilities FOR DELETE
  TO authenticated
  USING (true);

-- Jobs policies
CREATE POLICY "Authenticated users can read jobs"
  ON public.jobs FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert jobs"
  ON public.jobs FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update jobs"
  ON public.jobs FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete jobs"
  ON public.jobs FOR DELETE
  TO authenticated
  USING (true);

-- Engagements policies
CREATE POLICY "Authenticated users can read engagements"
  ON public.engagements FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert engagements"
  ON public.engagements FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update engagements"
  ON public.engagements FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete engagements"
  ON public.engagements FOR DELETE
  TO authenticated
  USING (true);

-- Exits policies
CREATE POLICY "Authenticated users can read exits"
  ON public.exits FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert exits"
  ON public.exits FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update exits"
  ON public.exits FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete exits"
  ON public.exits FOR DELETE
  TO authenticated
  USING (true);
