/*
  # Complete Initial Schema Setup
  
  Creates all essential tables and columns needed for the application to function.
  
  ## Tables Created
  - prospects: Main candidate/prospect tracking with full schema
  - engagements: Assignment tracking
  - facilities: Healthcare facility information
  - jobs: Job postings
  - exits: Exit tracking for completed assignments
  
  ## Security
  - RLS enabled on all tables
  - Authenticated users have full CRUD access
  - Anon users have read-only access where appropriate
*/

-- ============================================================================
-- ENUMS
-- ============================================================================

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'prospect_status') THEN
    CREATE TYPE prospect_status AS ENUM (
      'New', 'Contacted', 'Interested', 'Profile Updates', 
      'Submittal Ready', 'Submitted', 'Exited'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'engagement_status_type') THEN
    CREATE TYPE engagement_status_type AS ENUM (
      'Prospect', 'Submitted', 'Offer Extended', 'Signed',
      'Pre-Start (New)', 'Pre-Start (Extension)', 'Active', 
      'Contract Ended', 'Cancelled', 'Closed'
    );
  END IF;
END $$;

-- ============================================================================
-- PROSPECTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS prospects (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  candidate_id bigint UNIQUE NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  specialty text,
  profession text,
  recruiter text,
  notes text,
  status text DEFAULT 'New',
  home_state text,
  licenses text[],
  references_verified integer DEFAULT 0,
  profile_complete boolean DEFAULT false,
  available_start_date date,
  rto_notes text,
  reassignment_requested_at timestamptz,
  "order" integer DEFAULT 0,
  nova_url text,
  facility text,
  followup_stage text,
  last_contacted_at timestamptz,
  engagement_level text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE prospects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read all prospects"
  ON prospects FOR SELECT TO authenticated USING (true);

CREATE POLICY "Anon users can read all prospects"
  ON prospects FOR SELECT TO anon USING (true);

CREATE POLICY "Authenticated users can insert prospects"
  ON prospects FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Anon users can insert prospects"
  ON prospects FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Authenticated users can update prospects"
  ON prospects FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Anon users can update prospects"
  ON prospects FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users can delete prospects"
  ON prospects FOR DELETE TO authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_prospects_candidate_id ON prospects(candidate_id);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects(status);
CREATE INDEX IF NOT EXISTS idx_prospects_created_at ON prospects(created_at);
CREATE INDEX IF NOT EXISTS idx_prospects_specialty ON prospects(specialty);

-- ============================================================================
-- FACILITIES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS facilities (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL UNIQUE,
  city text NOT NULL,
  state text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE facilities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read facilities"
  ON facilities FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can manage facilities"
  ON facilities FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================================
-- JOBS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS jobs (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  facility_id bigint REFERENCES facilities(id) ON DELETE RESTRICT,
  job_id text UNIQUE,
  specialty text NOT NULL,
  shift text,
  hours_per_week integer,
  start_date date NOT NULL,
  duration_weeks integer DEFAULT 13,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read jobs"
  ON jobs FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can manage jobs"
  ON jobs FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_jobs_facility_id ON jobs(facility_id);
CREATE INDEX IF NOT EXISTS idx_jobs_specialty ON jobs(specialty);

-- ============================================================================
-- ENGAGEMENTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS engagements (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prospect_id bigint REFERENCES prospects(id) ON DELETE CASCADE,
  job_id bigint REFERENCES jobs(id) ON DELETE RESTRICT,
  status engagement_status_type DEFAULT 'Active',
  start_date date NOT NULL,
  end_date date NOT NULL,
  facility_name text,
  specialty text,
  bill_rate numeric(10,2),
  actual_margin numeric(5,2),
  notes text,
  extension_stage text DEFAULT 'not_started',
  is_looking_for_new_facility boolean DEFAULT false,
  is_exiting boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE engagements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read engagements"
  ON engagements FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can manage engagements"
  ON engagements FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_engagements_prospect_id ON engagements(prospect_id);
CREATE INDEX IF NOT EXISTS idx_engagements_status ON engagements(status);
CREATE INDEX IF NOT EXISTS idx_engagements_start_date ON engagements(start_date);

-- ============================================================================
-- EXITS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS exits (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prospect_id bigint REFERENCES prospects(id) ON DELETE CASCADE,
  engagement_id bigint REFERENCES engagements(id) ON DELETE SET NULL,
  exit_date date NOT NULL,
  exit_reason text,
  eligible_for_rehire boolean DEFAULT true,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE exits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read exits"
  ON exits FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can manage exits"
  ON exits FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_exits_prospect_id ON exits(prospect_id);
CREATE INDEX IF NOT EXISTS idx_exits_exit_date ON exits(exit_date DESC);