/*
  # Create outreach_templates table with RLS policies

  1. New Tables
    - `outreach_templates`
      - `id` (bigint, primary key)
      - `job_id` (text, unique)
      - `facility_name` (text)
      - `specialty` (text)
      - `location` (text)
      - `gross_weekly_pay` (numeric)
      - `email_subject` (text)
      - `email_body` (text)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on `outreach_templates` table
    - Add policies for authenticated users to perform all CRUD operations
    - Add policies for anonymous users to perform all CRUD operations (for development)

  3. Indexes
    - Add indexes on frequently queried columns for performance
*/

-- Create the outreach_templates table if it doesn't exist
CREATE TABLE IF NOT EXISTS outreach_templates (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  job_id text UNIQUE NOT NULL,
  facility_name text,
  specialty text,
  location text,
  gross_weekly_pay numeric,
  email_subject text,
  email_body text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE outreach_templates ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Authenticated users can read all outreach templates"
  ON outreach_templates
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert outreach templates"
  ON outreach_templates
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update outreach templates"
  ON outreach_templates
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete outreach templates"
  ON outreach_templates
  FOR DELETE
  TO authenticated
  USING (true);

-- Create policies for anonymous users (for development/testing)
CREATE POLICY "Anonymous users can read all outreach templates"
  ON outreach_templates
  FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Anonymous users can insert outreach templates"
  ON outreach_templates
  FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Anonymous users can update outreach templates"
  ON outreach_templates
  FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Anonymous users can delete outreach templates"
  ON outreach_templates
  FOR DELETE
  TO anon
  USING (true);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_outreach_templates_job_id ON outreach_templates(job_id);
CREATE INDEX IF NOT EXISTS idx_outreach_templates_facility_name ON outreach_templates(facility_name);
CREATE INDEX IF NOT EXISTS idx_outreach_templates_specialty ON outreach_templates(specialty);
CREATE INDEX IF NOT EXISTS idx_outreach_templates_updated_at ON outreach_templates(updated_at);