/*
  # Create actions table for engagement activity logging

  1. New Tables
    - `actions`
      - `id` (bigint, primary key, auto-generated)
      - `engagement_id` (bigint, foreign key to engagements)
      - `type` (action_type enum - Outreach, Margin Approval, Follow-up, Note)
      - `content` (text, optional description/notes)
      - `metadata` (jsonb, flexible data storage)
      - `created_at` (timestamp with timezone, defaults to now)

  2. Security
    - Enable RLS on `actions` table
    - Add policies for authenticated users to perform CRUD operations
    - Foreign key constraint ensures data integrity with engagements table
    - Cascade delete removes actions when engagement is deleted

  3. Features
    - Uses custom action_type enum for consistent categorization
    - JSONB metadata field for flexible additional data storage
    - Foreign key relationship maintains referential integrity
*/

-- Create the actions table for logging engagement activities
CREATE TABLE IF NOT EXISTS actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engagement_id bigint NOT NULL REFERENCES engagements(id) ON DELETE CASCADE,
  type action_type NOT NULL,
  content text,
  metadata jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Enable Row Level Security
ALTER TABLE actions ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for actions table
CREATE POLICY "Authenticated users can view all actions"
  ON actions
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert actions"
  ON actions
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update actions"
  ON actions
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete actions"
  ON actions
  FOR DELETE
  TO authenticated
  USING (true);

-- Create an index on engagement_id for better query performance
CREATE INDEX IF NOT EXISTS idx_actions_engagement_id ON actions(engagement_id);

-- Create an index on type for filtering by action type
CREATE INDEX IF NOT EXISTS idx_actions_type ON actions(type);

-- Create an index on created_at for chronological queries
CREATE INDEX IF NOT EXISTS idx_actions_created_at ON actions(created_at);