-- Healthcare Staffing Pipeline - Initial Consolidated Schema
-- Created: 2026-01-19
-- Purpose: Fresh start schema with all required tables, views, and functions.

-- ============================================================================
-- 1. EXTENSIONS & FUNCTIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 2. ENUMS
-- ============================================================================

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'prospect_status') THEN
    CREATE TYPE prospect_status AS ENUM (
      'New', 'Contacted', 'Interested', 'Profile Updates', 
      'Submittal Ready', 'Submitted', 'Exited'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'engagement_status_type') THEN
    CREATE TYPE engagement_status_type AS ENUM (
      'Prospect', 'Submitted', 'Offer Extended', 'Signed',
      'Pre-Start (New)', 'Pre-Start (Extension)', 'Active', 'ACTIVE',
      'Contract Ended', 'Cancelled', 'Closed'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'engagement_status') THEN
    CREATE TYPE engagement_status AS ENUM (
      'Prospect', 'Submitted', 'Offer Extended', 'Extension Request Sent',
      'Approved', 'Booked', 'Active', 'Contract Ended', 'Cancelled', 
      'Closed', 'Needs New Role'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'action_type') THEN
    CREATE TYPE action_type AS ENUM (
      'Outreach', 'Margin Approval', 'Follow-up', 'Note'
    );
  END IF;
END $$;

-- ============================================================================
-- 3. CORE TABLES
-- ============================================================================

-- PROSPECTS
CREATE TABLE IF NOT EXISTS prospects (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  candidate_id bigint UNIQUE NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  specialty text,
  profession text,
  recruiter text,
  notes text,
  status text DEFAULT 'New',
  home_state text,
  licenses text[],
  references_verified integer DEFAULT 0,
  profile_complete boolean DEFAULT false,
  available_start_date date,
  rto_notes text,
  reassignment_requested_at timestamptz,
  "order" integer DEFAULT 0,
  nova_url text,
  facility text,
  followup_stage text,
  last_contacted_at timestamptz,
  engagement_level text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- FACILITIES
CREATE TABLE IF NOT EXISTS facilities (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL UNIQUE,
  city text NOT NULL,
  state text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- JOBS
CREATE TABLE IF NOT EXISTS jobs (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  facility_id bigint REFERENCES facilities(id) ON DELETE RESTRICT,
  job_id text UNIQUE,
  specialty text NOT NULL,
  shift text,
  hours_per_week integer,
  start_date date NOT NULL,
  duration_weeks integer DEFAULT 13,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ENGAGEMENTS
CREATE TABLE IF NOT EXISTS engagements (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prospect_id bigint REFERENCES prospects(id) ON DELETE CASCADE,
  job_id bigint REFERENCES jobs(id) ON DELETE RESTRICT,
  status engagement_status_type DEFAULT 'Active',
  start_date date NOT NULL,
  end_date date NOT NULL,
  facility_name text,
  specialty text,
  bill_rate numeric(10,2),
  actual_margin numeric(5,2),
  notes text,
  extension_stage text DEFAULT 'not_started',
  is_looking_for_new_facility boolean DEFAULT false,
  is_exiting boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ACTIONS
CREATE TABLE IF NOT EXISTS actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engagement_id bigint NOT NULL REFERENCES engagements(id) ON DELETE CASCADE,
  type action_type NOT NULL,
  content text,
  metadata jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- EXITS
CREATE TABLE IF NOT EXISTS exits (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prospect_id bigint REFERENCES prospects(id) ON DELETE CASCADE,
  engagement_id bigint REFERENCES engagements(id) ON DELETE SET NULL,
  exit_date date NOT NULL,
  exit_reason text,
  eligible_for_rehire boolean DEFAULT true,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- FOLLOW_UPS
CREATE TABLE IF NOT EXISTS follow_ups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id bigint NOT NULL,
  recruiter_id uuid NOT NULL,
  follow_up_type text NOT NULL CHECK (follow_up_type IN ('active', 'rotation')),
  scheduled_date date NOT NULL,
  completed boolean DEFAULT false,
  completed_at timestamptz,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT fk_candidate FOREIGN KEY (candidate_id) REFERENCES prospects(candidate_id) ON DELETE CASCADE,
  CONSTRAINT fk_recruiter FOREIGN KEY (recruiter_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- INTERESTED_CLICKS
CREATE TABLE IF NOT EXISTS interested_clicks (
  id bigserial PRIMARY KEY,
  application_id bigint UNIQUE NOT NULL,
  application_date date NOT NULL,
  job_id text NOT NULL,
  candidate_name text NOT NULL,
  candidate_email text NOT NULL,
  candidate_homestate text,
  job_city text,
  job_state text,
  profession text,
  specialty text,
  recruiter_name text,
  recruiter_email text,
  last_note text,
  last_note_date timestamptz,
  last_note_by text,
  status text DEFAULT 'New',
  facility_name text,
  shift_type text,
  start_date text,
  end_date text,
  pay_range text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- PAY_PACKAGES
CREATE TABLE IF NOT EXISTS pay_packages (
  id bigserial PRIMARY KEY,
  job_id text UNIQUE NOT NULL,
  facility_name text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  specialty text NOT NULL,
  start_date text,
  end_date text,
  shift_type text,
  hours_per_week integer NOT NULL DEFAULT 40,
  taxable_hourly_rate numeric(10, 2) NOT NULL,
  meals_weekly numeric(10, 2),
  housing_weekly numeric(10, 2),
  total_stipend numeric(10, 2) NOT NULL DEFAULT 0,
  gross_weekly_pay numeric(10, 2) NOT NULL,
  completion_bonus numeric(10, 2),
  source text DEFAULT 'manual',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================================
-- 4. VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW follow_ups_dashboard AS
SELECT 
  f.id,
  f.candidate_id,
  f.recruiter_id,
  f.follow_up_type,
  f.scheduled_date,
  f.completed,
  f.completed_at,
  f.notes,
  f.created_at,
  f.updated_at,
  p.name AS candidate_name,
  p.email AS candidate_email,
  p.phone AS candidate_phone,
  p.specialty AS candidate_specialty,
  p.profession AS candidate_profession,
  p.status AS candidate_status,
  p.nova_url AS candidate_nova_url,
  u.email AS recruiter_email,
  COALESCE(u.raw_user_meta_data->>'full_name', u.email) AS recruiter_name
FROM follow_ups f
JOIN prospects p ON f.candidate_id = p.candidate_id
JOIN auth.users u ON f.recruiter_id = u.id;

CREATE OR REPLACE VIEW priority_interested_clicks AS
SELECT 
  ic.*,
  CASE 
    WHEN ic.last_note_date >= NOW() - INTERVAL '7 days' THEN true
    ELSE false
  END AS recruiter_contacted_recently,
  EXTRACT(DAY FROM NOW() - ic.application_date::timestamptz)::integer AS days_since_application
FROM interested_clicks ic
WHERE ic.status != 'Closed'
ORDER BY ic.application_date DESC;

-- ============================================================================
-- 5. RPC FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION get_follow_ups_by_recruiter(recruiter_uuid uuid)
RETURNS TABLE (
  id uuid,
  candidate_id bigint,
  recruiter_id uuid,
  follow_up_type text,
  scheduled_date date,
  completed boolean,
  completed_at timestamptz,
  notes text,
  created_at timestamptz,
  updated_at timestamptz,
  candidate_name text,
  candidate_email text,
  candidate_phone text,
  candidate_specialty text,
  candidate_profession text,
  candidate_status text,
  candidate_nova_url text,
  recruiter_email text,
  recruiter_name text
)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT * FROM follow_ups_dashboard
  WHERE recruiter_id = recruiter_uuid
  ORDER BY scheduled_date ASC, created_at DESC;
$$;

CREATE OR REPLACE FUNCTION complete_follow_up(follow_up_uuid uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result_row follow_ups;
BEGIN
  UPDATE follow_ups
  SET 
    completed = true,
    completed_at = now(),
    updated_at = now()
  WHERE id = follow_up_uuid
    AND recruiter_id = auth.uid()
  RETURNING * INTO result_row;
  
  IF result_row IS NULL THEN
    RAISE EXCEPTION 'Follow-up not found or access denied';
  END IF;
  
  RETURN row_to_json(result_row);
END;
$$;

CREATE OR REPLACE FUNCTION reschedule_follow_up(follow_up_uuid uuid, new_date date)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result_row follow_ups;
BEGIN
  UPDATE follow_ups
  SET 
    scheduled_date = new_date,
    updated_at = now()
  WHERE id = follow_up_uuid
    AND recruiter_id = auth.uid()
  RETURNING * INTO result_row;
  
  IF result_row IS NULL THEN
    RAISE EXCEPTION 'Follow-up not found or access denied';
  END IF;
  
  RETURN row_to_json(result_row);
END;
$$;

CREATE OR REPLACE FUNCTION create_follow_up(
  p_candidate_id bigint,
  p_follow_up_type text,
  p_scheduled_date date,
  p_notes text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result_row follow_ups;
BEGIN
  INSERT INTO follow_ups (
    candidate_id,
    recruiter_id,
    follow_up_type,
    scheduled_date,
    notes
  ) VALUES (
    p_candidate_id,
    auth.uid(),
    p_follow_up_type,
    p_scheduled_date,
    p_notes
  )
  RETURNING * INTO result_row;
  
  RETURN row_to_json(result_row);
END;
$$;

CREATE OR REPLACE FUNCTION calculate_pay_package(
  p_job_id text,
  p_state text,
  p_city text,
  p_profession text,
  p_specialty text,
  p_target_gross numeric,
  p_hours_per_week integer DEFAULT 36
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_taxable_hourly numeric;
  v_meals_weekly numeric;
  v_housing_weekly numeric;
  v_total_stipend numeric;
  v_gross_weekly numeric;
  v_state_tax_rate numeric;
BEGIN
  v_state_tax_rate := 0.25;
  CASE 
    WHEN p_state IN ('CA', 'NY', 'MA') THEN
      v_meals_weekly := 350;
      v_housing_weekly := 1500;
    WHEN p_state IN ('TX', 'FL', 'AZ') THEN
      v_meals_weekly := 300;
      v_housing_weekly := 1200;
    ELSE
      v_meals_weekly := 325;
      v_housing_weekly := 1350;
  END CASE;
  v_total_stipend := v_meals_weekly + v_housing_weekly;
  v_taxable_hourly := (p_target_gross - v_total_stipend) / p_hours_per_week;
  IF v_taxable_hourly < 25 THEN
    v_taxable_hourly := 25;
  END IF;
  v_gross_weekly := (v_taxable_hourly * p_hours_per_week) + v_total_stipend;
  RETURN jsonb_build_object(
    'job_id', p_job_id,
    'taxable_hourly', ROUND(v_taxable_hourly, 2),
    'meals_weekly', ROUND(v_meals_weekly, 2),
    'housing_weekly', ROUND(v_housing_weekly, 2),
    'total_stipend', ROUND(v_total_stipend, 2),
    'gross_weekly', ROUND(v_gross_weekly, 2)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.bulk_update_extension_stage(
  engagement_ids bigint[],
  new_stage text
)
RETURNS TABLE (
  engagement_id bigint,
  extension_stage text,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF new_stage NOT IN ('not_started', 'outreach', 'interested', 'requested', 'signed') THEN
    RAISE EXCEPTION 'Invalid extension_stage value: %', new_stage;
  END IF;

  RETURN QUERY
  UPDATE public.engagements
  SET
    extension_stage = new_stage,
    updated_at = NOW()
  WHERE id = ANY(engagement_ids)
  RETURNING id, engagements.extension_stage, engagements.updated_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.toggle_assignment_flag(
  engagement_id bigint,
  flag_name text,
  flag_value boolean
)
RETURNS TABLE (
  id bigint,
  is_looking_for_new_facility boolean,
  is_exiting boolean,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF flag_name NOT IN ('looking', 'exiting') THEN
    RAISE EXCEPTION 'Invalid flag_name: %. Must be "looking" or "exiting"', flag_name;
  END IF;

  IF flag_name = 'looking' THEN
    RETURN QUERY
    UPDATE public.engagements
    SET
      is_looking_for_new_facility = flag_value,
      updated_at = NOW()
    WHERE engagements.id = engagement_id
    RETURNING
      engagements.id,
      engagements.is_looking_for_new_facility,
      engagements.is_exiting,
      engagements.updated_at;
  ELSIF flag_name = 'exiting' THEN
    RETURN QUERY
    UPDATE public.engagements
    SET
      is_exiting = flag_value,
      updated_at = NOW()
    WHERE engagements.id = engagement_id
    RETURNING
      engagements.id,
      engagements.is_looking_for_new_facility,
      engagements.is_exiting,
      engagements.updated_at;
  END IF;
END;
$$;

-- ============================================================================
-- 6. SECURITY & POLICIES
-- ============================================================================

-- RLS
ALTER TABLE prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE engagements ENABLE ROW LEVEL SECURITY;
ALTER TABLE exits ENABLE ROW LEVEL SECURITY;
ALTER TABLE follow_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE interested_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE pay_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE actions ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public access to prospects" ON prospects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to facilities" ON facilities FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to jobs" ON jobs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to engagements" ON engagements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to exits" ON exits FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to follow_ups" ON follow_ups FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to interested_clicks" ON interested_clicks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to pay_packages" ON pay_packages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access to actions" ON actions FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 7. TRIGGERS
-- ============================================================================

CREATE TRIGGER update_prospects_updated_at BEFORE UPDATE ON prospects FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_facilities_updated_at BEFORE UPDATE ON facilities FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_jobs_updated_at BEFORE UPDATE ON jobs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_engagements_updated_at BEFORE UPDATE ON engagements FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_exits_updated_at BEFORE UPDATE ON exits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_follow_ups_updated_at BEFORE UPDATE ON follow_ups FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_interested_clicks_updated_at BEFORE UPDATE ON interested_clicks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pay_packages_updated_at BEFORE UPDATE ON pay_packages FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- 8. INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_prospects_candidate_id ON prospects(candidate_id);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects(status);
CREATE INDEX IF NOT EXISTS idx_engagements_prospect_id ON engagements(prospect_id);
CREATE INDEX IF NOT EXISTS idx_follow_ups_date ON follow_ups(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_interested_clicks_application_id ON interested_clicks(application_id);
CREATE INDEX IF NOT EXISTS idx_pay_packages_job_id ON pay_packages(job_id);

-- Grants
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, authenticated, anon, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, authenticated, anon, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, authenticated, anon, service_role;
