/*
  # Create engagements table

  1. New Tables
    - `engagements`
      - `id` (bigint, primary key, auto-generated)
      - `candidate_name` (text, required)
      - `facility_name` (text, required) 
      - `specialty` (text, required)
      - `job_id` (text, optional identifier for matching)
      - `status` (engagement_status enum, defaults to 'Prospect')
      - `created_at` (timestamp with timezone, defaults to now)

  2. Security
    - Enable RLS on `engagements` table
    - Add policies for authenticated users to manage engagement data
*/

-- The main table for tracking all engagements
CREATE TABLE IF NOT EXISTS engagements (
  id bigint generated by default as identity primary key,
  candidate_name text not null,
  facility_name text not null,
  specialty text not null,
  job_id text, -- A reliable identifier for matching
  status engagement_status default 'Prospect' not null,
  created_at timestamp with time zone default now() not null
);

-- Enable Row Level Security
ALTER TABLE engagements ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read all engagements
CREATE POLICY "Users can read all engagements"
  ON engagements
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow authenticated users to insert new engagements
CREATE POLICY "Users can insert engagements"
  ON engagements
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Allow authenticated users to update engagements
CREATE POLICY "Users can update engagements"
  ON engagements
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Allow authenticated users to delete engagements
CREATE POLICY "Users can delete engagements"
  ON engagements
  FOR DELETE
  TO authenticated
  USING (true);